### PR TITLE
Support installation on Windows

### LINKED ISSUE #13: Can't install on windows
Hey, when I run cargo install on windows I'm having issues with termion

```
   Compiling termion v1.5.5
error[E0433]: failed to resolve: maybe a missing crate `sys`?
  --> C:\Users\xxxx\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.5\src\lib.rs:24:9
   |
24 | pub use sys::size::terminal_size;
   |         ^^^ maybe a missing crate `sys`?
```

I haven't tried to install it on linux yet, is this something that may be exclusive to my computer or something?

At the end it says it has failed to compile dijo v0.1.3

### PR DESCRIPTION
**Pull request by filalex77**
Close #13.

After testing `feature/windows` branch locally for some time, I can safely say that it's ready. So I rebased it onto latest `master` and added a CI job for Windows releases. Hope it helps!

### CODE REVIEW

**Comment by NerdyPepper** [comment]
Thanks for your work on this! I have added some bits to conditionally compile with `termion` on linux and `crossterm` on windows, (`crossterm` causes the screen to flash on refresh).

**Comment by NerdyPepper** [comment]
Ah, that wouldn't quite work, rust tries to build `cursive` with the `termion` feature on all platforms, even though it doesn't need it on windows. Currently, `cfg(target_os = "...")` in `Cargo.toml` is a nightly only feature.

**Comment by NerdyPepper** [comment]
I have updated `dijo` to now support compile time feature flags, `unix` for `termion` and `windows` for `crossterm`, but I receive this on completion of CI builds on windows:
```   Compiling dijo v0.2.1 (D:\a\dijo\dijo)
    Finished release [optimized] target(s) in 5m 01s
C:\ProgramData\Chocolatey\lib\mingw\tools\install\mingw64\x86_64-w64-mingw32\bin\strip.exe: 'target/release/dijo': No such file
##[error]Process completed with exit code 1.
```

should this perhaps be `target\release\dijo`?

**Comment by NerdyPepper** [comment]
> should this perhaps be target\release\dijo?

It was `target/release/dijo.exe`.

I have sort of worked this out by switching to the pancurses backend, the build is working fine with your CI additions!

**Comment by filalex77** [comment]
Thanks for figuring it out @NerdyPepper!

**Pull request merged**
