### PR TITLE
Add nix support

### PR DESCRIPTION
**Pull request by noeleont**
Hei there 

This PR adds support for the nix package manager, so people can simply run

```shell
nix-build default.nix
```

I wasn't sure if the instructions belong into the readme.md or in the wiki, what to you think?

### CODE REVIEW

**Comment by NerdyPepper** [comment]
@noeleont thank you for your contributions!

@Infinisil I am not too familiar with nix and its package management system, but is this PR different from what you were working on?

**Comment by Infinisil** [comment]
Yeah this is a bit different. What I'll be doing is adding dijo to [nixpkgs](https://github.com/NixOS/nixpkgs), which is the standard package repository for Nix, which also builds all packages with CI for distribution. This notably also works without any Nix involvement from the project itself.

This PR on the other hand adds a way for the project itself to specify how the package can be built with Nix. Ideally the Nix expressions here would be the same as the ones for nixpkgs, but this is often problematic due to restrictions in nixpkgs. Namely Nix expressions would have to be synchronized manually (nixpkgs doesn't allow fetching Nix expressions from upstream repos), and a certain type of evaluation isn't allowed (IFD, which the expressions in this PR use).

So this PR is largely irrelevant for nixpkgs in its current state. In addition, I personally wouldn't merge this PR unless somebody is willing to maintain these Nix expressions in the future, perhaps with CI verifying that it builds with Nix.

**Comment by Infinisil** [comment]
Just opened the nixpkgs PR for it: https://github.com/NixOS/nixpkgs/pull/93597

**Comment by NerdyPepper** [comment]
@noeleont I would prefer the package definitions for NixOS to exist on the nixpkgs repo for the same reasons as @Infinisil mentioned:

 - nixpkgs has a more rigorous method of verifying/testing package definitions
 - maintaining nix expressions alongside `dijo` might get a little out of hand

Nevertheless, thanks a lot @noeleont and @Infinisil for all the help with packaging `dijo` for NixOS!

**Pull request closed without merging**
